<?php

namespace ContainerTTFKUh7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.biBHM6Y.App\Entity\Color' shared service.
     *
     * @return \App\Entity\Color
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.biBHM6Y": it references class "App\\Entity\\Color" but no such service exists.');
    }
}
