<?php

namespace ContainerNkjNxl9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Ym44_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Ym44.P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Ym44.P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.0Ym44.P.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.0Ym44.P": it references class "App\\Entity\\Client" but no such service exists.'],
        ], [
            'client' => 'App\\Entity\\Client',
        ]);
    }
}
